name: php-framework
recipe: lemp
config:
  via: nginx
  config:
    vhosts: .lando/nginx.conf
  php: '8.2'
  database: mysql
  xdebug: true
services:
  phpmyadmin:
    type: phpmyadmin
  redis:
    type: redis